name: Build .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore library
      run: dotnet restore ExpressParser/ExpressParser.csproj
    - name: Build library (as NuGet package)
      run: dotnet --no-restore pack ExpressParser/ExpressParser.csproj
    - name: Restore CLI example
      run: dotnet restore ExpressParser/ExpressParser.csproj
    - name: Build CLI example
      run: dotnet --no-restore build ExpressParser/ExpressParser.csproj
