name: NuGet
on:
  push:
    branches: [ nuget ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Prepare
      run: mkdir -p ExpressParser/bin/Debug
    - name: Restore
      run: dotnet restore ExpressParser/ExpressParser.csproj
    - name: Build
      run: dotnet pack -c Release --no-restore ExpressParser/ExpressParser.csproj
    - name: Push NuGet
      run: |
        dotnet nuget add source --username KirillAldashkin --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/OWNER/index.json"
        dotnet nuget push "bin/Release/OctocatApp.1.0.0.nupkg"  --api-key ${{ secrets.GITHUB_TOKEN }} --source "github"
